import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/sections/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: "400", // You can set the specific weights you need
  variable: "--font-inter", // Enable variable fonts if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} min-h-screen flex flex-col`}>
        <main className="flex-grow">
          <NavBar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
