import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/sections/Footer";
import ParallaxFalls from "@/components/sections/ParallaxFalls";

const inter = Inter({
  subsets: ["latin"],
  weight: "400", // You can set the specific weights you need
  variable: "--font-inter", // Enable variable fonts if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${inter.variable} min-h-screen flex flex-col overflow-x-hidden`}
      >
        <main className="flex-grow">
          <NavBar />
          {children}
        </main>
        <Footer />
        <ParallaxFalls />
      </body>
    </html>
  );
}
